version: 2
executorType: docker
containerInfo:
  - image: rohara/pantheon:0.1
    env:
      - TERMINUS_ENV=ci{{$CIRCLE_BUILD_NUM}}
      - TERMINUS_SITE=migrate-pantheon-d8
      - PANTHEON_D7_SITE=migrate-pantheon-d7
      - PANTHEON_D7_BRANCH=dev
stages:
  build:
    workDir: /home/ubuntu/migrate_pantheon
    steps:
      - type: checkout
      - type: shell
        command: |
          composer install --no-interaction
          terminus auth login --machine-token=